/**
 * AL Form 40 PDF filler.
 *
 * Fills the Alabama Form 40 (Individual Income Tax Return) template
 * from computed Form 40 results. Falls back to programmatic generation
 * when no template is available.
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { Form40Result } from '../../rules/2025/al/form40'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic fallback generator ──────────────────────────────

async function generateForm40(
  taxReturn: TaxReturn,
  form: Form40Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const crimson = rgb(0.6, 0.1, 0.1) // Alabama crimson

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false, color = black) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color })
  }

  const drawLine = (label: string, value: number, bold = false) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, bold)
    y -= 16
  }

  const drawSection = (title: string) => {
    y -= 8
    draw(title, 72, 11, true, crimson)
    y -= 4
    page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
    y -= 16
  }

  draw('Alabama Form 40', 72, 16, true, crimson)
  y -= 14
  page.drawText('Individual Income Tax Return — 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: crimson })
  y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 12

  if (form.residencyType !== 'full-year') {
    draw(`Residency: ${form.residencyType === 'part-year' ? 'Part-Year Resident' : 'Nonresident'}`, 72, 9)
    draw(`Apportionment: ${(form.apportionmentRatio * 100).toFixed(1)}%`, 300, 9)
    y -= 12
  }

  // Income section
  drawSection('Income')
  drawLine('Federal AGI', form.federalAGI)
  if (form.alAdditions > 0) drawLine('AL Additions', form.alAdditions)
  if (form.alSubtractions > 0) drawLine('AL Subtractions', form.alSubtractions)
  if (form.federalTaxDeduction > 0) drawLine('Federal Tax Deduction', form.federalTaxDeduction)
  drawLine('Alabama AGI', form.alAGI, true)

  // Deductions & Exemptions section
  drawSection('Deductions & Exemptions')
  drawLine('Standard Deduction', form.standardDeduction)
  drawLine('Personal Exemption', form.personalExemption)
  if (form.dependentExemption > 0) drawLine('Dependent Exemption', form.dependentExemption)
  drawLine('Alabama Taxable Income', form.alTaxableIncome, true)

  // Tax section
  drawSection('Tax & Credits')
  drawLine('AL Tax (2%/4%/5%)', form.alTax)
  drawLine('Tax After Credits', form.taxAfterCredits, true)

  // Payments section
  drawSection('Payments')
  drawLine('AL State Withholding', form.stateWithholding)

  // Result section
  drawSection('Result')
  if (form.overpaid > 0) {
    drawLine('Refund', form.overpaid, true)
  } else if (form.amountOwed > 0) {
    drawLine('Amount You Owe', form.amountOwed, true)
  } else {
    drawLine('Balance', 0)
  }

  y -= 20
  page.drawText('Generated by OpenTax — for review. File using official AL Form 40.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const alFormCompiler: StateFormCompiler = {
  stateCode: 'AL',

  templateFiles: ['form40.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as Form40Result

    // Use programmatic generation for 2025 tax year.
    // Template-based filling can be added when field positions are calibrated.
    const doc = await generateForm40(taxReturn, form)

    return {
      doc,
      forms: [
        {
          formId: 'AL Form 40',
          sequenceNumber: 'AL-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
