/**
 * AR Form AR1000F PDF filler.
 *
 * Fills the official Arkansas Form AR1000F template from computed results.
 * Uses programmatic generation as the primary path.
 */

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { FormAR1000FResult } from '../../rules/2025/ar/formAR1000F'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

async function generateFormAR1000F(
  taxReturn: TaxReturn,
  form: FormAR1000FResult,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const darkBlue = rgb(0.1, 0.15, 0.35)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, opts?: { font?: typeof font; color?: typeof black }) => {
    page.drawText(text, { x, y, size, font: opts?.font ?? font, color: opts?.color ?? black })
  }

  const drawLine = (label: string, lineNum: string, value: string, opts?: { bold?: boolean }) => {
    draw(`Line ${lineNum}`, 72, 9, { color: gray })
    draw(label, 120, 9, opts?.bold ? { font: fontBold } : undefined)
    draw(value, 460, 9, { font: fontBold })
    y -= 16
  }

  draw('Arkansas Form AR1000F', 72, 16, { font: fontBold, color: darkBlue })
  y -= 12
  draw('Full-Year Resident Individual Income Tax Return — 2025', 72, 10, { color: gray })
  y -= 6
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.5, color: darkBlue })
  y -= 20

  draw('Taxpayer Information', 72, 11, { font: fontBold })
  y -= 16
  draw(`Name: ${taxReturn.taxpayer.firstName} ${taxReturn.taxpayer.lastName}`, 90, 9)
  y -= 14
  draw(`SSN: ${formatSSN(taxReturn.taxpayer.ssn || '000000000')}`, 90, 9)
  draw(`Filing Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 14

  y -= 8
  draw('Income', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('Federal AGI', '1', `$${formatDollars(form.federalAGI)}`)
  if (form.arSubtractions > 0) {
    drawLine('AR subtractions', '3', `($${formatDollars(form.arSubtractions)})`)
  }
  drawLine('Arkansas AGI', '4', `$${formatDollars(form.arAGI)}`, { bold: true })
  drawLine('AR standard deduction', '5', `$${formatDollars(form.arStandardDeduction)}`)
  drawLine('Taxable income', '7', `$${formatDollars(form.arTaxableIncome)}`, { bold: true })

  y -= 8
  draw('Tax, Credits, and Payments', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('AR tax (graduated)', '8', `$${formatDollars(form.arTax)}`)
  if (form.personalTaxCredit > 0) {
    drawLine(`Personal tax credit (${form.numExemptions} x $29)`, '10', `($${formatDollars(form.personalTaxCredit)})`)
  }
  if (form.arEITC > 0) {
    drawLine('AR EITC', '13', `($${formatDollars(form.arEITC)})`)
  }
  drawLine('Tax after credits', '15', `$${formatDollars(form.taxAfterCredits)}`, { bold: true })
  if (form.stateWithholding > 0) {
    drawLine('AR withholding', '22', `$${formatDollars(form.stateWithholding)}`)
  }

  y -= 8
  if (form.overpaid > 0) {
    drawLine('Refund', '31', `$${formatDollars(form.overpaid)}`, { bold: true })
  } else if (form.amountOwed > 0) {
    drawLine('Amount owed', '29', `$${formatDollars(form.amountOwed)}`, { bold: true })
  } else {
    drawLine('Balance', '', '$0')
  }

  y -= 20
  draw('Generated by OpenTax for review. File with official AR Form AR1000F.', 72, 7, { color: gray })

  return pdfDoc
}

export const arFormCompiler: StateFormCompiler = {
  stateCode: 'AR',
  templateFiles: ['ar1000f.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as FormAR1000FResult
    const doc = await generateFormAR1000F(taxReturn, form)

    return {
      doc,
      forms: [{
        formId: stateResult.formLabel,
        sequenceNumber: 'AR-01',
        pageCount: doc.getPageCount(),
      }],
    }
  },
}
