import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { Form760Result } from '../../rules/2025/va/form760'
import type { StateCompiledForms, StateFormCompiler, StateFormTemplates } from '../stateCompiler'
import { filingStatusLabel, formatDollars, formatSSN } from '../helpers'

async function generateForm760(taxReturn: TaxReturn, form760: Form760Result): Promise<PDFDocument> {
  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  const blue = rgb(0.1, 0.15, 0.35)
  const gray = rgb(0.45, 0.45, 0.45)

  let y = 750
  const draw = (text: string, x: number, size = 9, useBold = false, color = rgb(0, 0, 0)) => {
    page.drawText(text, { x, y, size, font: useBold ? bold : font, color })
  }

  const line = (label: string, value: number, num?: string) => {
    draw(num ? `Line ${num}` : '', 72, 8, false, gray)
    draw(label, 130)
    draw(`$${formatDollars(value)}`, 460, 9, true)
    y -= 15
  }

  const isPY = form760.residencyType !== 'full-year'
  draw(isPY ? 'Virginia Form 760PY (Part-Year)' : 'Virginia Form 760', 72, 16, true, blue)
  y -= 14
  draw('Individual Income Tax Return — 2025', 72, 10, false, gray)
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.5, color: blue })
  y -= 18

  draw(`Name: ${taxReturn.taxpayer.firstName} ${taxReturn.taxpayer.lastName}`, 72)
  y -= 13
  draw(`SSN: ${formatSSN(taxReturn.taxpayer.ssn || '000000000')}`, 72)
  draw(`Filing status: ${filingStatusLabel(taxReturn.filingStatus)}`, 280)
  y -= 18

  draw('Income & Deductions', 72, 11, true, blue)
  y -= 16
  line('Federal AGI', form760.federalAGI, '1')
  line('Virginia AGI', form760.vaAGI, '7')
  if (form760.vaSourceIncome !== undefined) {
    line('Virginia-source income', form760.vaSourceIncome, '9')
  }
  line(`VA ${form760.deductionMethod} deduction`, form760.deductionUsed, '10')
  line('Virginia taxable income', form760.vaTaxableIncome, '15')

  y -= 8
  draw('Tax, Credits, Payments', 72, 11, true, blue)
  y -= 16
  line('Virginia income tax', form760.vaTax, '16')
  line('Exemptions/credits', form760.exemptions, '24')
  line('Tax after credits', form760.taxAfterCredits, '25')
  if (form760.stateWithholding > 0) line('Virginia withholding', form760.stateWithholding, '30')

  y -= 8
  draw('Result', 72, 11, true, blue)
  y -= 16
  if (form760.overpaid > 0) line('Refund', form760.overpaid, '34')
  else if (form760.amountOwed > 0) line('Amount owed', form760.amountOwed, '35')
  else line('Balance', 0)

  y -= 25
  draw('Generated by OpenTax for review. File using official Virginia forms.', 72, 7, false, gray)

  return doc
}

export const vaFormCompiler: StateFormCompiler = {
  stateCode: 'VA',
  templateFiles: ['f760.pdf'],
  async compile(taxReturn: TaxReturn, stateResult: StateComputeResult, templates: StateFormTemplates): Promise<StateCompiledForms> {
    void templates
    const form760 = stateResult.detail as Form760Result
    const doc = await generateForm760(taxReturn, form760)
    return {
      doc,
      forms: [{
        formId: form760.residencyType === 'full-year' ? 'VA Form 760' : 'VA Form 760PY',
        sequenceNumber: 'VA-01',
        pageCount: doc.getPageCount(),
      }],
    }
  },
}
