/**
 * Ohio Form IT 1040 PDF filler.
 *
 * Generates a programmatic Ohio IT 1040 (Individual Income Tax Return)
 * summary PDF from computed Form IT 1040 results.
 */

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { FormIT1040Result } from '../../rules/2025/oh/formIT1040'
import type { StateCompiledForms, StateFormCompiler, StateFormTemplates } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic fallback generator ──────────────────────────────

async function generateFormIT1040OH(
  taxReturn: TaxReturn,
  form: FormIT1040Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.2, 0.45)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color: black })
  }

  const drawLine = (label: string, value: number) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, true)
    y -= 16
  }

  draw('Ohio Form IT 1040', 72, 16, true)
  y -= 14
  page.drawText('Individual Income Tax Return — 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: blue })
  y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 12

  // ── Income ───────────────────────────────────────────────────
  draw('Income', 72, 11, true)
  y -= 16
  drawLine('Federal AGI', form.federalAGI)
  drawLine('Ohio Deductions (SS Exemption)', form.ssExemption)
  drawLine('Ohio AGI', form.ohAGI)

  // ── Tax ──────────────────────────────────────────────────────
  y -= 8
  draw('Tax', 72, 11, true)
  y -= 16
  drawLine('Ohio Taxable Income', form.ohTaxableIncome)
  drawLine('Ohio Tax Before Credits', form.ohTaxBeforeCredits)
  if (form.personalExemptionCredit > 0) drawLine('Personal Exemption Credit', form.personalExemptionCredit)
  if (form.jointFilingCredit > 0) drawLine('Joint Filing Credit', form.jointFilingCredit)
  drawLine('Ohio Tax After Credits', form.taxAfterCredits)

  // ── Payments ─────────────────────────────────────────────────
  y -= 8
  draw('Payments', 72, 11, true)
  y -= 16
  drawLine('OH State Withholding', form.stateWithholding)

  // ── Result ───────────────────────────────────────────────────
  y -= 8
  draw('Result', 72, 11, true)
  y -= 16
  if (form.overpaid > 0) drawLine('Refund', form.overpaid)
  else drawLine('Amount You Owe', form.amountOwed)

  y -= 20
  page.drawText('Generated by OpenTax — for review. File using official OH Form IT 1040.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const ohFormCompiler: StateFormCompiler = {
  stateCode: 'OH',

  templateFiles: ['it1040.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as FormIT1040Result
    const doc = await generateFormIT1040OH(taxReturn, form)

    return {
      doc,
      forms: [
        {
          formId: 'OH Form IT 1040',
          sequenceNumber: 'OH-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
