import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { Form502Result } from '../../rules/2025/md/form502'
import type { StateCompiledForms, StateFormCompiler, StateFormTemplates } from '../stateCompiler'
import { filingStatusLabel, formatDollars, formatSSN } from '../helpers'

async function generateForm502(taxReturn: TaxReturn, form: Form502Result): Promise<PDFDocument> {
  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.15, 0.35)

  let y = 750
  const draw = (t: string, x: number, size = 9, b = false, color = rgb(0, 0, 0)) => {
    page.drawText(t, { x, y, size, font: b ? bold : font, color })
  }
  const line = (label: string, value: string) => {
    draw(label, 90)
    draw(value, 450, 9, true)
    y -= 16
  }

  const isNonresident = form.residencyType === 'nonresident'
  draw(isNonresident ? 'Maryland Form 505' : 'Maryland Form 502', 72, 16, true, blue)
  y -= 14
  draw(`2025 ${isNonresident ? 'Nonresident' : 'Resident/Part-Year'} Income Tax Return`, 72, 10, false, gray)
  y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72)
  y -= 14
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}   Filing: ${filingStatusLabel(taxReturn.filingStatus)}`, 72)
  y -= 14
  draw(`Address: ${tp.address.street}, ${tp.address.city}, ${tp.address.state} ${tp.address.zip}`, 72)
  y -= 22

  draw('Income', 72, 11, true, blue)
  y -= 16
  line('Federal AGI', `$${formatDollars(form.federalAGI)}`)
  line('Maryland AGI', `$${formatDollars(form.mdAGI)}`)
  if (form.mdSourceIncome !== undefined) line('Maryland-source income', `$${formatDollars(form.mdSourceIncome)}`)

  y -= 8
  draw('Deductions & Exemptions', 72, 11, true, blue)
  y -= 16
  line(`Deduction (${form.deductionMethod})`, `$${formatDollars(form.deductionUsed)}`)
  line('Total exemptions', `$${formatDollars(form.totalExemptions)}`)
  line('Taxable income', `$${formatDollars(form.mdTaxableIncome)}`)

  y -= 8
  draw('Tax & Result', 72, 11, true, blue)
  y -= 16
  line('MD state tax', `$${formatDollars(form.mdStateTax)}`)
  line('MD local tax', `$${formatDollars(form.mdLocalTax)}`)
  line('Tax after credits', `$${formatDollars(form.taxAfterCredits)}`)
  line('State withholding', `$${formatDollars(form.stateWithholding)}`)
  if (form.overpaid > 0) line('Refund', `$${formatDollars(form.overpaid)}`)
  else if (form.amountOwed > 0) line('Amount owed', `$${formatDollars(form.amountOwed)}`)
  else line('Balance', '$0')

  y -= 24
  draw('Generated by OpenTax (programmatic summary). File official MD forms when required.', 72, 7, false, gray)

  return doc
}

export const mdFormCompiler: StateFormCompiler = {
  stateCode: 'MD',
  templateFiles: ['502.pdf', '505.pdf'],
  async compile(taxReturn: TaxReturn, stateResult: StateComputeResult, _templates: StateFormTemplates): Promise<StateCompiledForms> {
    const form = stateResult.detail as Form502Result
    const doc = await generateForm502(taxReturn, form)
    const formId = form.residencyType === 'nonresident' ? 'MD Form 505' : 'MD Form 502'

    return {
      doc,
      forms: [{ formId, sequenceNumber: 'MD-01', pageCount: doc.getPageCount() }],
    }
  },
}
