import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { PA40Result } from '../../rules/2025/pa/pa40'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

async function generatePA40(
  taxReturn: TaxReturn,
  pa40: PA40Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const darkBlue = rgb(0.1, 0.15, 0.35)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, opts?: { font?: typeof font; color?: typeof black }) => {
    page.drawText(text, { x, y, size, font: opts?.font ?? font, color: opts?.color ?? black })
  }

  const drawLine = (label: string, value: string, opts?: { bold?: boolean }) => {
    draw(label, 90, 10, opts?.bold ? { font: fontBold } : undefined)
    draw(value, 430, 10, { font: fontBold })
    y -= 18
  }

  draw('Pennsylvania PA-40', 72, 16, { font: fontBold, color: darkBlue })
  y -= 12
  draw('Personal Income Tax Return — 2025 (Generated summary)', 72, 10, { color: gray })
  y -= 10
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.5, color: darkBlue })
  y -= 20

  draw('Taxpayer Information', 72, 11, { font: fontBold })
  y -= 16
  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 90, 9)
  y -= 14
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 90, 9)
  draw(`Filing Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 14
  draw(`Address: ${tp.address.street}, ${tp.address.city}, ${tp.address.state} ${tp.address.zip}`, 90, 9)
  y -= 22

  draw('Computation', 72, 11, { font: fontBold, color: darkBlue })
  y -= 16
  drawLine('PA Total Taxable Income (Line 9)', `$${formatDollars(pa40.totalPATaxableIncome)}`)
  drawLine('PA Taxable Income', `$${formatDollars(pa40.adjustedTaxableIncome)}`)
  drawLine('PA Tax (3.07%)', `$${formatDollars(pa40.paTax)}`)
  drawLine('PA State Withholding', `$${formatDollars(pa40.stateWithholding)}`)
  y -= 6

  if (pa40.overpaid > 0) {
    drawLine('PA Refund', `$${formatDollars(pa40.overpaid)}`, { bold: true })
  } else if (pa40.amountOwed > 0) {
    drawLine('PA Amount You Owe', `$${formatDollars(pa40.amountOwed)}`, { bold: true })
  } else {
    drawLine('PA Balance', '$0.00', { bold: true })
  }

  y -= 18
  draw('Generated by OpenTax. Review against official PA-40 instructions before filing.', 72, 8, { color: gray })

  return pdfDoc
}

export const paFormCompiler: StateFormCompiler = {
  stateCode: 'PA',
  templateFiles: ['pa40.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const pa40 = stateResult.detail as PA40Result
    const doc = await generatePA40(taxReturn, pa40)

    return {
      doc,
      forms: [
        {
          formId: 'PA-40',
          sequenceNumber: 'PA-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
