import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { StateCompiledForms, StateFormCompiler, StateFormTemplates } from '../stateCompiler'
import type { Form1Result } from '../../rules/2025/ma/form1'
import { filingStatusLabel, formatDollars, formatSSN } from '../helpers'

async function generateForm1(taxReturn: TaxReturn, form1: Form1Result): Promise<PDFDocument> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const page = doc.addPage([612, 792])

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.08, 0.18, 0.36)

  let y = 750
  const draw = (text: string, x: number, size = 9, f = font, color = black) => {
    page.drawText(text, { x, y, size, font: f, color })
  }
  const line = (label: string, val: number, tag?: string) => {
    if (tag) draw(tag, 72, 9, font, gray)
    draw(label, 120)
    draw(`$${formatDollars(val)}`, 455, 9, bold)
    y -= 16
  }

  const isPart = form1.residencyType === 'part-year'
  draw(isPart ? 'Massachusetts Form 1-NR/PY' : 'Massachusetts Form 1', 72, 16, bold, blue)
  y -= 14
  draw('Resident / Nonresident Personal Income Tax Return (generated summary)', 72, 9, font, gray)
  y -= 16

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72)
  y -= 13
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}   Filing Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 72)
  y -= 13
  draw(`Address: ${tp.address.street}, ${tp.address.city}, ${tp.address.state} ${tp.address.zip}`, 72)
  y -= 22

  draw('Income', 72, 11, bold, blue)
  y -= 16
  line('Federal AGI', form1.federalAGI)
  line('Massachusetts AGI', form1.maAGI)
  if (form1.maSourceIncome !== undefined) {
    line('MA-source income (apportioned)', form1.maSourceIncome)
    draw(`Apportionment ratio: ${(form1.apportionmentRatio * 100).toFixed(1)}%`, 120, 8, font, gray)
    y -= 14
  }

  y -= 4
  draw('Tax', 72, 11, bold, blue)
  y -= 16
  line('Personal exemption', form1.personalExemption)
  line('MA taxable income', form1.maTaxableIncome)
  line('Income tax (5%)', form1.maIncomeTax)
  line('Tax after credits', form1.taxAfterCredits)

  y -= 4
  draw('Payments & Result', 72, 11, bold, blue)
  y -= 16
  line('State withholding', form1.stateWithholding)
  if (form1.overpaid > 0) line('Refund', form1.overpaid)
  if (form1.amountOwed > 0) line('Amount owed', form1.amountOwed)
  if (form1.overpaid === 0 && form1.amountOwed === 0) line('Balance', 0)

  y -= 24
  draw('Generated by OpenTax for review. File using official Massachusetts DOR forms.', 72, 7, font, gray)

  return doc
}

export const maFormCompiler: StateFormCompiler = {
  stateCode: 'MA',
  templateFiles: ['form1.pdf'],
  async compile(taxReturn: TaxReturn, stateResult: StateComputeResult, _templates: StateFormTemplates): Promise<StateCompiledForms> {
    const form1 = stateResult.detail as Form1Result
    const doc = await generateForm1(taxReturn, form1)
    return {
      doc,
      forms: [{
        formId: form1.residencyType === 'part-year' ? 'MA Form 1-NR/PY' : 'MA Form 1',
        sequenceNumber: 'MA-01',
        pageCount: doc.getPageCount(),
      }],
    }
  },
}
