import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { FormD40Result } from '../../rules/2025/dc/formd40'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { filingStatusLabel, formatDollars, formatSSN } from '../helpers'

async function generateFormD40(taxReturn: TaxReturn, d40: FormD40Result): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const page = pdfDoc.addPage([612, 792])

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.08, 0.15, 0.35)

  let y = 750
  const draw = (text: string, x: number, size: number, bold = false, color = black) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color })
  }
  const drawLine = (label: string, line: string, value: string) => {
    draw(`Line ${line}`, 72, 9, false, gray)
    draw(label, 120, 9)
    draw(value, 450, 9, true)
    y -= 16
  }

  draw('District of Columbia Form D-40', 72, 16, true, blue); y -= 14
  draw('Individual Income Tax Return — 2025', 72, 10, false, gray); y -= 14
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.5, color: blue }); y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 14
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Filing status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 14
  draw(`Address: ${tp.address.street}, ${tp.address.city}, ${tp.address.state} ${tp.address.zip}`, 72, 9)
  y -= 22

  drawLine('Federal AGI', '1', `$${formatDollars(d40.federalAGI)}`)
  drawLine('DC AGI', '4', `$${formatDollars(d40.dcAGI)}`)
  drawLine('Deduction', '5', `$${formatDollars(d40.deductionUsed)}`)
  drawLine('DC taxable income', '6', `$${formatDollars(d40.dcTaxableIncome)}`)
  drawLine('DC tax', '12', `$${formatDollars(d40.dcTax)}`)

  if (d40.commuterExempt) {
    draw('Reciprocity override: MD/VA nonresident commuter (DC tax = $0).', 120, 8, false, gray)
    y -= 14
  }

  drawLine('DC withholding', '30', `$${formatDollars(d40.stateWithholding)}`)
  drawLine('Total payments', '36', `$${formatDollars(d40.totalPayments)}`)

  if (d40.overpaid > 0) drawLine('Refund', '40', `$${formatDollars(d40.overpaid)}`)
  else if (d40.amountOwed > 0) drawLine('Amount owed', '44', `$${formatDollars(d40.amountOwed)}`)
  else drawLine('Balance', '44', '$0')

  y -= 20
  draw('Generated by OpenTax for review. File with official DC OTR forms.', 72, 7, false, gray)

  return pdfDoc
}

export const dcFormCompiler: StateFormCompiler = {
  stateCode: 'DC',
  templateFiles: ['d40.pdf'],
  async compile(taxReturn: TaxReturn, stateResult: StateComputeResult, _templates: StateFormTemplates): Promise<StateCompiledForms> {
    const d40 = stateResult.detail as FormD40Result
    const doc = await generateFormD40(taxReturn, d40)
    return {
      doc,
      forms: [{ formId: 'DC Form D-40', sequenceNumber: 'DC-01', pageCount: doc.getPageCount() }],
    }
  },
}
