import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { Form500Result } from '../../rules/2025/ga/form500'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

async function generateForm500(
  taxReturn: TaxReturn,
  form500: Form500Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const darkBlue = rgb(0.1, 0.15, 0.35)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, opts?: { font?: typeof font; color?: typeof black }) => {
    page.drawText(text, { x, y, size, font: opts?.font ?? font, color: opts?.color ?? black })
  }

  const drawLine = (label: string, lineNum: string, value: string, opts?: { bold?: boolean }) => {
    draw(`Line ${lineNum}`, 72, 9, { color: gray })
    draw(label, 120, 9, opts?.bold ? { font: fontBold } : undefined)
    draw(value, 460, 9, { font: fontBold })
    y -= 16
  }

  draw('Georgia Form 500', 72, 16, { font: fontBold, color: darkBlue })
  y -= 12
  draw('Individual Income Tax Return — 2025', 72, 10, { color: gray })
  y -= 6
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.5, color: darkBlue })
  y -= 20

  draw('Taxpayer Information', 72, 11, { font: fontBold })
  y -= 16
  draw(`Name: ${taxReturn.taxpayer.firstName} ${taxReturn.taxpayer.lastName}`, 90, 9)
  y -= 14
  draw(`SSN: ${formatSSN(taxReturn.taxpayer.ssn || '000000000')}`, 90, 9)
  draw(`Filing Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 14

  y -= 8
  draw('Income', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('Federal AGI', '5', `$${formatDollars(form500.federalAGI)}`)
  if (form500.gaAdjustments.additions > 0) {
    drawLine('Schedule 1 additions', '6', `$${formatDollars(form500.gaAdjustments.additions)}`)
  }
  if (form500.gaAdjustments.subtractions > 0) {
    drawLine('Schedule 1 subtractions', '8', `($${formatDollars(form500.gaAdjustments.subtractions)})`)
  }
  drawLine('Georgia AGI', '9', `$${formatDollars(form500.gaAGI)}`, { bold: true })

  y -= 8
  draw('Deductions & Exemptions', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('Deduction used', '12', `$${formatDollars(form500.deductionUsed)}`)
  if (form500.dependentExemption > 0) {
    drawLine('Dependent exemption', '13', `$${formatDollars(form500.dependentExemption)}`)
  }
  drawLine('Taxable income', '15', `$${formatDollars(form500.gaTaxableIncome)}`, { bold: true })

  y -= 8
  draw('Tax, Credits, and Payments', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('GA tax (5.19%)', '16', `$${formatDollars(form500.gaTax)}`)
  if (form500.totalCredits > 0) {
    drawLine('Credits', '20', `($${formatDollars(form500.totalCredits)})`)
  }
  drawLine('Tax after credits', '21', `$${formatDollars(form500.taxAfterCredits)}`, { bold: true })

  if (form500.stateWithholding > 0) {
    drawLine('GA withholding', '24', `$${formatDollars(form500.stateWithholding)}`)
  }
  drawLine('Total payments', '27', `$${formatDollars(form500.totalPayments)}`, { bold: true })

  if (form500.overpaid > 0) {
    drawLine('Refund', '29', `$${formatDollars(form500.overpaid)}`, { bold: true })
  } else if (form500.amountOwed > 0) {
    drawLine('Amount owed', '30', `$${formatDollars(form500.amountOwed)}`, { bold: true })
  } else {
    drawLine('Balance', '', '$0')
  }

  y -= 20
  draw('Generated by OpenTax for review. File with official GA Form 500.', 72, 7, { color: gray })

  return pdfDoc
}

export const gaFormCompiler: StateFormCompiler = {
  stateCode: 'GA',
  templateFiles: ['GA-Form-500-2025.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form500 = stateResult.detail as Form500Result
    const doc = await generateForm500(taxReturn, form500)

    return {
      doc,
      forms: [{
        formId: stateResult.formLabel,
        sequenceNumber: 'GA-01',
        pageCount: doc.getPageCount(),
      }],
    }
  },
}
