/**
 * IA Form IA 1040 PDF filler.
 *
 * Fills the official Iowa Form IA 1040 (Individual Income Tax Return)
 * template from computed IA 1040 results. Falls back to programmatic
 * generation when no template is available.
 *
 * The official IA 1040 PDF does not have AcroForm fields, so this filler
 * uses programmatic generation exclusively.
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { IA1040Result } from '../../rules/2025/ia/ia1040'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic generator ──────────────────────────────────────

async function generateIA1040(
  taxReturn: TaxReturn,
  form: IA1040Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.2, 0.45)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color: black })
  }

  const drawLine = (label: string, value: number) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, true)
    y -= 16
  }

  draw('Iowa Form IA 1040', 72, 16, true)
  y -= 14
  page.drawText('Individual Income Tax Return — 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: blue })
  y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 12

  if (form.residencyType !== 'full-year') {
    draw(`Residency: ${form.residencyType}`, 72, 9)
    draw(`Apportionment: ${(form.apportionmentRatio * 100).toFixed(2)}%`, 300, 9)
    y -= 12
  }

  y -= 4
  draw('Income', 72, 11, true)
  y -= 16
  drawLine('Federal AGI', form.federalAGI)
  if (form.iaAdditions > 0) drawLine('IA Additions', form.iaAdditions)
  if (form.iaSubtractions > 0) drawLine('IA Subtractions', form.iaSubtractions)
  drawLine('Iowa Net Income', form.iaNetIncome)

  y -= 8
  draw('Deductions & Tax', 72, 11, true)
  y -= 16
  drawLine('Iowa Standard Deduction', form.standardDeduction)
  drawLine('Iowa Taxable Income', form.iaTaxableIncome)
  drawLine('Iowa Tax (3.8%)', form.iaTax)

  y -= 8
  draw('Credits', 72, 11, true)
  y -= 16
  drawLine(`Personal Exemption Credit (${form.exemptionCount} x $40)`, form.personalExemptionCredit)
  if (form.iaEIC > 0) drawLine('IA Earned Income Credit', form.iaEIC)
  drawLine('Total Credits', form.totalCredits)
  drawLine('Tax After Credits', form.taxAfterCredits)

  y -= 8
  draw('Payments', 72, 11, true)
  y -= 16
  drawLine('IA State Withholding', form.stateWithholding)

  y -= 8
  draw('Result', 72, 11, true)
  y -= 16
  if (form.overpaid > 0) drawLine('Refund', form.overpaid)
  else drawLine('Amount You Owe', form.amountOwed)

  y -= 20
  page.drawText('Generated by OpenTax — for review. File using official IA Form IA 1040.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const iaFormCompiler: StateFormCompiler = {
  stateCode: 'IA',

  templateFiles: ['ia1040.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as IA1040Result

    // The official IA 1040 PDF does not have AcroForm fields,
    // so we always use programmatic generation.
    const doc = await generateIA1040(taxReturn, form)

    return {
      doc,
      forms: [
        {
          formId: 'IA Form IA 1040',
          sequenceNumber: 'IA-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
