/**
 * Indiana Form IT-40 PDF filler.
 *
 * Fills the official Indiana Form IT-40 (Individual Income Tax Return)
 * template from computed IT-40 results. Falls back to programmatic
 * generation when no template is available.
 */

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { PDFFont, PDFPage } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { IT40Result } from '../../rules/2025/in/it40'
import type { StateCompiledForms, StateFormCompiler, StateFormTemplates } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic fallback generator ──────────────────────────────

async function generateIT40(
  taxReturn: TaxReturn,
  it40: IT40Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.2, 0.45)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color: black })
  }

  const drawLine = (label: string, value: number) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, true)
    y -= 16
  }

  // Title
  draw('Indiana Form IT-40', 72, 16, true)
  y -= 14
  page.drawText('Individual Income Tax Return — 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: blue })
  y -= 20

  // Taxpayer info
  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 12

  // Residency
  if (it40.residencyType !== 'full-year') {
    draw(`Residency: ${it40.residencyType}`, 72, 9)
    draw(`Apportionment: ${(it40.apportionmentRatio * 100).toFixed(1)}%`, 300, 9)
    y -= 12
  }

  y -= 4

  // Income section
  draw('Income', 72, 11, true)
  y -= 16
  drawLine('Federal AGI', it40.federalAGI)
  if (it40.totalAdditions > 0) {
    drawLine('Additions to Income', it40.totalAdditions)
  }
  drawLine('Indiana AGI', it40.inAGI)

  y -= 4

  // Exemptions & Subtractions
  draw('Exemptions & Subtractions', 72, 11, true)
  y -= 16
  drawLine('Personal Exemptions', it40.personalExemptions)
  if (it40.dependentExemptions > 0) {
    drawLine('Dependent Exemptions', it40.dependentExemptions)
  }
  if (it40.age65Exemptions > 0) {
    drawLine('Age 65+ Exemptions', it40.age65Exemptions)
  }
  if (it40.blindExemptions > 0) {
    drawLine('Blind Exemptions', it40.blindExemptions)
  }
  if (it40.ssExemption > 0) {
    drawLine('Social Security Exemption', it40.ssExemption)
  }
  if (it40.usGovInterest > 0) {
    drawLine('US Gov Interest Subtraction', it40.usGovInterest)
  }
  drawLine('Indiana Taxable Income', it40.inTaxableIncome)

  y -= 4

  // Tax & Credits
  draw('Tax & Credits', 72, 11, true)
  y -= 16
  drawLine('Indiana State Tax (3.05%)', it40.inTax)
  if (it40.countyTax > 0) {
    drawLine('County Tax', it40.countyTax)
  }
  if (it40.inEITC > 0) {
    drawLine('Indiana EITC (10% of federal)', it40.inEITC)
  }
  if (it40.elderlyCreditAmount > 0) {
    drawLine('Elderly Credit', it40.elderlyCreditAmount)
  }
  drawLine('Tax After Credits', it40.taxAfterCredits)

  y -= 4

  // Payments
  draw('Payments', 72, 11, true)
  y -= 16
  if (it40.stateWithholding > 0) {
    drawLine('IN State Withholding', it40.stateWithholding)
  }
  if (it40.countyWithholding > 0) {
    drawLine('County Withholding', it40.countyWithholding)
  }

  y -= 4

  // Result
  draw('Result', 72, 11, true)
  y -= 16
  if (it40.overpaid > 0) drawLine('Refund', it40.overpaid)
  else drawLine('Amount You Owe', it40.amountOwed)

  y -= 20
  page.drawText('Generated by OpenTax — for review. File using official IN Form IT-40.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── Template-based filler ────────────────────────────────────────

/**
 * Draw text on a PDF page at the specified coordinates.
 */
function drawAt(
  page: PDFPage,
  font: PDFFont,
  x: number,
  y: number,
  value: string,
  size = 9,
): void {
  try {
    page.drawText(value, {
      x,
      y,
      size,
      font,
      color: rgb(0, 0, 0),
    })
  } catch {
    // Skip silently if draw fails
  }
}

/**
 * Draw a dollar-formatted value. Skips if zero.
 */
function drawDollar(
  page: PDFPage,
  font: PDFFont,
  x: number,
  y: number,
  amountCents: number,
  size = 9,
): void {
  if (amountCents === 0) return
  drawAt(page, font, x, y, formatDollars(amountCents), size)
}

async function fillIT40Template(
  templateBytes: Uint8Array,
  taxReturn: TaxReturn,
  it40: IT40Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.load(templateBytes, { ignoreEncryption: true })
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const pages = pdfDoc.getPages()

  // The official IT-40 PDF layout varies; use coordinate-based overlay.
  // These coordinates are approximate and may need calibration against
  // the actual template.
  if (pages.length === 0) return pdfDoc

  const p0 = pages[0]
  const tp = taxReturn.taxpayer

  // Header — taxpayer name and SSN
  drawAt(p0, font, 80, 680, `${tp.firstName} ${tp.lastName}`, 9)
  drawAt(p0, font, 400, 680, formatSSN(tp.ssn || '000000000'), 9)

  // Address
  drawAt(p0, font, 80, 660, tp.address.street, 9)
  drawAt(p0, font, 80, 645, `${tp.address.city}, ${tp.address.state} ${tp.address.zip}`, 9)

  // Spouse (if MFJ)
  if (taxReturn.spouse) {
    const sp = taxReturn.spouse
    drawAt(p0, font, 80, 625, `${sp.firstName} ${sp.lastName}`, 9)
    drawAt(p0, font, 400, 625, formatSSN(sp.ssn), 9)
  }

  // Income and tax amounts — approximate positions, may need calibration
  // against the specific IT-40 template revision.
  drawDollar(p0, font, 420, 500, it40.federalAGI)
  drawDollar(p0, font, 420, 480, it40.inAGI)
  drawDollar(p0, font, 420, 400, it40.inTaxableIncome)
  drawDollar(p0, font, 420, 380, it40.inTax)
  drawDollar(p0, font, 420, 360, it40.taxAfterCredits)

  // Note: Precise field positions for the official Indiana IT-40 template
  // require calibration per the specific form revision. The programmatic
  // fallback above provides full coverage.

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const inFormCompiler: StateFormCompiler = {
  stateCode: 'IN',

  templateFiles: ['it40.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const it40 = stateResult.detail as IT40Result

    // Use official template when available, fall back to programmatic generation
    const templateBytes = templates.templates.get('it40')
    const doc = templateBytes
      ? await fillIT40Template(templateBytes, taxReturn, it40)
      : await generateIT40(taxReturn, it40)

    return {
      doc,
      forms: [
        {
          formId: 'IN Form IT-40',
          sequenceNumber: 'IN-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
