/**
 * LA Form IT-540 PDF filler.
 *
 * Fills the Louisiana Form IT-540 (Resident Individual Income Tax Return)
 * template from computed IT-540 results. Falls back to programmatic
 * generation when no template is available.
 *
 * Note: The PDF template is for 2024 (old graduated rates) but our
 * computation uses 2025 rules (flat 3.0%). The programmatic fallback
 * accurately reflects 2025 reform amounts.
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { IT540Result } from '../../rules/2025/la/it540'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic fallback generator ──────────────────────────────

async function generateIT540(
  taxReturn: TaxReturn,
  form: IT540Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.2, 0.45)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color: black })
  }

  const drawLine = (label: string, value: number) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, true)
    y -= 16
  }

  draw('Louisiana Form IT-540', 72, 16, true)
  y -= 14
  page.drawText('Resident Individual Income Tax Return — 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: blue })
  y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 12

  if (form.residencyType !== 'full-year') {
    draw(`Residency: ${form.residencyType === 'part-year' ? 'Part-Year Resident' : 'Nonresident'}`, 72, 9)
    draw(`Apportionment: ${(form.apportionmentRatio * 100).toFixed(1)}%`, 300, 9)
    y -= 12
  }

  y -= 4
  draw('Income', 72, 11, true)
  y -= 16
  drawLine('Federal AGI', form.federalAGI)
  if (form.laAdditions > 0) drawLine('LA Additions', form.laAdditions)
  if (form.laSubtractions > 0) drawLine('LA Subtractions', form.laSubtractions)
  drawLine('Louisiana AGI', form.laAGI)

  y -= 8
  draw('Deductions & Tax', 72, 11, true)
  y -= 16
  drawLine('Standard Deduction', form.standardDeduction)
  drawLine('Louisiana Taxable Income', form.laTaxableIncome)
  drawLine('Louisiana Tax (3.0%)', form.laTax)

  if (form.totalCredits > 0) {
    y -= 8
    draw('Credits', 72, 11, true)
    y -= 16
    if (form.dependentCredit > 0) drawLine('Dependent Credit', form.dependentCredit)
    if (form.laEIC > 0) drawLine('LA Earned Income Credit', form.laEIC)
  }

  drawLine('Tax After Credits', form.taxAfterCredits)

  y -= 8
  draw('Payments', 72, 11, true)
  y -= 16
  drawLine('LA State Withholding', form.stateWithholding)

  y -= 8
  draw('Result', 72, 11, true)
  y -= 16
  if (form.overpaid > 0) drawLine('Refund', form.overpaid)
  else drawLine('Amount You Owe', form.amountOwed)

  y -= 20
  page.drawText('Generated by OpenTax — for review. File using official LA Form IT-540.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const laFormCompiler: StateFormCompiler = {
  stateCode: 'LA',

  templateFiles: ['it540.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as IT540Result

    // The 2024 template uses old graduated rates; use programmatic generation
    // that accurately reflects 2025 flat rate reform amounts.
    // Template-based filling can be added when the 2025 IT-540 form is released.
    const doc = await generateIT540(taxReturn, form)

    return {
      doc,
      forms: [
        {
          formId: 'LA Form IT-540',
          sequenceNumber: 'LA-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
