/**
 * MI Form MI-1040 PDF filler.
 *
 * Fills the official Michigan Form MI-1040 (Individual Income Tax Return)
 * template from computed MI-1040 results. Falls back to programmatic
 * generation when no template is available.
 */

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { MI1040Result } from '../../rules/2025/mi/mi1040'
import type { StateCompiledForms, StateFormCompiler, StateFormTemplates } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic generator (fallback when no template PDF available) ──

async function generateMI1040(
  taxReturn: TaxReturn,
  form: MI1040Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.2, 0.45)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color: black })
  }

  const drawLine = (label: string, value: number) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, true)
    y -= 16
  }

  // ── Title ───────────────────────────────────────────────────
  draw('Michigan Form MI-1040', 72, 16, true)
  y -= 14
  page.drawText('Individual Income Tax Return \u2014 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: blue })
  y -= 20

  // ── Taxpayer info ───────────────────────────────────────────
  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 6

  if (taxReturn.spouse) {
    y -= 6
    draw(`Spouse: ${taxReturn.spouse.firstName} ${taxReturn.spouse.lastName}`, 72, 9)
    draw(`SSN: ${formatSSN(taxReturn.spouse.ssn)}`, 300, 9)
    y -= 6
  }

  y -= 6

  // ── Residency ───────────────────────────────────────────────
  const residencyLabel =
    form.residencyType === 'full-year' ? 'Full-Year Resident' :
    form.residencyType === 'part-year' ? `Part-Year Resident (${(form.apportionmentRatio * 100).toFixed(1)}%)` :
    'Nonresident'
  draw(`Residency: ${residencyLabel}`, 72, 9)
  y -= 16

  // ── Income ──────────────────────────────────────────────────
  draw('Income & Adjustments', 72, 11, true)
  y -= 16
  drawLine('Federal AGI', form.federalAGI)
  if (form.miAdditions > 0) drawLine('Michigan Additions', form.miAdditions)
  if (form.miSubtractions > 0) drawLine('Michigan Subtractions', form.miSubtractions)
  drawLine('Michigan AGI', form.miAGI)
  y -= 4

  // ── Exemptions ──────────────────────────────────────────────
  draw('Exemptions', 72, 11, true)
  y -= 16
  draw(`Personal Exemptions: ${form.numExemptions} x $5,600`, 72, 10)
  draw(`$${formatDollars(form.personalExemptions)}`, 460, 10, true)
  y -= 16

  // ── Tax ─────────────────────────────────────────────────────
  draw('Tax Computation', 72, 11, true)
  y -= 16
  drawLine('Michigan Taxable Income', form.miTaxableIncome)
  drawLine('Michigan Tax (4.25%)', form.miTax)

  if (form.miEITC > 0) {
    drawLine('Michigan EITC (30% of Federal)', form.miEITC)
  }
  drawLine('Tax After Credits', form.taxAfterCredits)
  y -= 4

  // ── Payments ────────────────────────────────────────────────
  draw('Payments', 72, 11, true)
  y -= 16
  drawLine('MI State Withholding', form.stateWithholding)
  y -= 4

  // ── Result ──────────────────────────────────────────────────
  draw('Result', 72, 11, true)
  y -= 16
  if (form.overpaid > 0) {
    drawLine('Refund', form.overpaid)
  } else if (form.amountOwed > 0) {
    drawLine('Amount You Owe', form.amountOwed)
  } else {
    draw('No tax owed, no refund', 72, 10)
    y -= 16
  }

  // ── Footer ──────────────────────────────────────────────────
  y -= 20
  page.drawText('Generated by OpenTax \u2014 for review. File using official MI Form MI-1040.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const miFormCompiler: StateFormCompiler = {
  stateCode: 'MI',

  templateFiles: ['mi1040.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as MI1040Result

    // Use programmatic generation (template filling can be added later
    // when the MI-1040 PDF field mappings are calibrated)
    const doc = await generateMI1040(taxReturn, form)

    return {
      doc,
      forms: [
        {
          formId: 'MI Form MI-1040',
          sequenceNumber: 'MI-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
