/**
 * MS Form 80-105 PDF filler.
 *
 * Fills the official Mississippi Form 80-105 (Resident Individual Income Tax Return)
 * template from computed Form 80-105 results. Falls back to programmatic
 * generation when no template is available.
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { Form80105Result } from '../../rules/2025/ms/form80105'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic fallback generator ──────────────────────────────

async function generateForm80105(
  taxReturn: TaxReturn,
  form: Form80105Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.2, 0.45)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color: black })
  }

  const drawLine = (label: string, value: number) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, true)
    y -= 16
  }

  draw('Mississippi Form 80-105', 72, 16, true)
  y -= 14
  page.drawText('Resident Individual Income Tax Return — 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: blue })
  y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 12

  if (form.residencyType !== 'full-year') {
    draw(`Residency: ${form.residencyType}`, 72, 9)
    if (form.apportionmentRatio < 1) {
      draw(`Apportionment: ${(form.apportionmentRatio * 100).toFixed(2)}%`, 300, 9)
    }
    y -= 12
  }

  y -= 4
  draw('Income', 72, 11, true)
  y -= 16
  drawLine('Federal AGI', form.federalAGI)
  if (form.msAdditions > 0) drawLine('MS Additions', form.msAdditions)
  if (form.msSubtractions > 0) drawLine('MS Subtractions', form.msSubtractions)
  drawLine('Mississippi AGI', form.msAGI)

  y -= 8
  draw('Deductions & Exemptions', 72, 11, true)
  y -= 16
  drawLine('Standard Deduction', form.standardDeduction)
  drawLine('Personal Exemption', form.personalExemption)
  if (form.dependentExemption > 0) {
    drawLine(`Dependent Exemptions (${taxReturn.dependents.length} x $1,500)`, form.dependentExemption)
  }
  drawLine('Mississippi Taxable Income', form.msTaxableIncome)

  y -= 8
  draw('Tax', 72, 11, true)
  y -= 16
  if (form.msExemptAmount > 0) {
    drawLine('Exempt Amount (first $10,000)', form.msExemptAmount)
  }
  drawLine('Income Subject to Tax', form.msIncomeSubjectToTax)
  drawLine('Mississippi Tax (4.4%)', form.msTax)
  drawLine('Tax After Credits', form.taxAfterCredits)

  y -= 8
  draw('Payments', 72, 11, true)
  y -= 16
  drawLine('MS State Withholding', form.stateWithholding)

  y -= 8
  draw('Result', 72, 11, true)
  y -= 16
  if (form.overpaid > 0) drawLine('Refund', form.overpaid)
  else drawLine('Amount You Owe', form.amountOwed)

  y -= 20
  page.drawText('Generated by OpenTax — for review. File using official MS Form 80-105.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const msFormCompiler: StateFormCompiler = {
  stateCode: 'MS',

  templateFiles: ['form80105.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as Form80105Result

    // For now, always use programmatic generation since we haven't
    // mapped the AcroForm fields in the official MS 80-105 PDF yet.
    // TODO: Map AcroForm fields and add template-based filling.
    const doc = await generateForm80105(taxReturn, form)

    return {
      doc,
      forms: [
        {
          formId: 'MS Form 80-105',
          sequenceNumber: 'MS-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
