/**
 * NE Form 1040N PDF filler.
 *
 * Fills the official Nebraska Form 1040N template from computed results.
 * Uses programmatic generation as the primary path.
 */

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { Form1040NResult } from '../../rules/2025/ne/form1040N'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

async function generateForm1040N(
  taxReturn: TaxReturn,
  form: Form1040NResult,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const darkBlue = rgb(0.1, 0.15, 0.35)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, opts?: { font?: typeof font; color?: typeof black }) => {
    page.drawText(text, { x, y, size, font: opts?.font ?? font, color: opts?.color ?? black })
  }

  const drawLine = (label: string, lineNum: string, value: string, opts?: { bold?: boolean }) => {
    draw(`Line ${lineNum}`, 72, 9, { color: gray })
    draw(label, 120, 9, opts?.bold ? { font: fontBold } : undefined)
    draw(value, 460, 9, { font: fontBold })
    y -= 16
  }

  draw('Nebraska Form 1040N', 72, 16, { font: fontBold, color: darkBlue })
  y -= 12
  draw('Individual Income Tax Return — 2025', 72, 10, { color: gray })
  y -= 6
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.5, color: darkBlue })
  y -= 20

  draw('Taxpayer Information', 72, 11, { font: fontBold })
  y -= 16
  draw(`Name: ${taxReturn.taxpayer.firstName} ${taxReturn.taxpayer.lastName}`, 90, 9)
  y -= 14
  draw(`SSN: ${formatSSN(taxReturn.taxpayer.ssn || '000000000')}`, 90, 9)
  draw(`Filing Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 14
  if (taxReturn.spouse) {
    draw(`Spouse: ${taxReturn.spouse.firstName} ${taxReturn.spouse.lastName}`, 90, 9)
    y -= 14
  }

  y -= 8
  draw('Income', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('Federal AGI', '1', `$${formatDollars(form.federalAGI)}`)
  if (form.neSubtractions > 0) {
    drawLine('NE subtractions', '3', `($${formatDollars(form.neSubtractions)})`)
  }
  drawLine('Nebraska AGI', '4', `$${formatDollars(form.neAGI)}`, { bold: true })
  drawLine('NE standard deduction', '5', `$${formatDollars(form.neDeduction)}`)
  drawLine('Taxable income', '6', `$${formatDollars(form.neTaxableIncome)}`, { bold: true })

  y -= 8
  draw('Tax, Credits, and Payments', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('NE tax (graduated)', '7', `$${formatDollars(form.neTax)}`)
  if (form.personalExemptionCredit > 0) {
    drawLine(`Personal exemption credit (${form.numExemptions} x $157)`, '10', `($${formatDollars(form.personalExemptionCredit)})`)
  }
  drawLine('Tax after credits', '14', `$${formatDollars(form.taxAfterCredits)}`, { bold: true })
  if (form.neEITC > 0) {
    drawLine('NE EITC (refundable)', '26', `$${formatDollars(form.neEITC)}`)
  }
  if (form.stateWithholding > 0) {
    drawLine('NE withholding', '28', `$${formatDollars(form.stateWithholding)}`)
  }
  drawLine('Total payments', '32', `$${formatDollars(form.totalPayments)}`, { bold: true })

  y -= 8
  if (form.overpaid > 0) {
    drawLine('Refund', '35', `$${formatDollars(form.overpaid)}`, { bold: true })
  } else if (form.amountOwed > 0) {
    drawLine('Amount owed', '38', `$${formatDollars(form.amountOwed)}`, { bold: true })
  } else {
    drawLine('Balance', '', '$0')
  }

  y -= 20
  draw('Generated by OpenTax for review. File with official NE Form 1040N.', 72, 7, { color: gray })

  return pdfDoc
}

export const neFormCompiler: StateFormCompiler = {
  stateCode: 'NE',
  templateFiles: ['1040n.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as Form1040NResult
    const doc = await generateForm1040N(taxReturn, form)

    return {
      doc,
      forms: [{
        formId: stateResult.formLabel,
        sequenceNumber: 'NE-01',
        pageCount: doc.getPageCount(),
      }],
    }
  },
}
