/**
 * NM Form PIT-1 PDF filler.
 *
 * Fills the official New Mexico Form PIT-1 template from computed results.
 * Uses programmatic generation as the primary path.
 */

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { FormPIT1Result } from '../../rules/2025/nm/formPIT1'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

async function generateFormPIT1(
  taxReturn: TaxReturn,
  form: FormPIT1Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const darkBlue = rgb(0.1, 0.15, 0.35)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, opts?: { font?: typeof font; color?: typeof black }) => {
    page.drawText(text, { x, y, size, font: opts?.font ?? font, color: opts?.color ?? black })
  }

  const drawLine = (label: string, lineNum: string, value: string, opts?: { bold?: boolean }) => {
    draw(`Line ${lineNum}`, 72, 9, { color: gray })
    draw(label, 120, 9, opts?.bold ? { font: fontBold } : undefined)
    draw(value, 460, 9, { font: fontBold })
    y -= 16
  }

  draw('New Mexico Form PIT-1', 72, 16, { font: fontBold, color: darkBlue })
  y -= 12
  draw('Personal Income Tax Return — 2025', 72, 10, { color: gray })
  y -= 6
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.5, color: darkBlue })
  y -= 20

  draw('Taxpayer Information', 72, 11, { font: fontBold })
  y -= 16
  draw(`Name: ${taxReturn.taxpayer.firstName} ${taxReturn.taxpayer.lastName}`, 90, 9)
  y -= 14
  draw(`SSN: ${formatSSN(taxReturn.taxpayer.ssn || '000000000')}`, 90, 9)
  draw(`Filing Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 14

  y -= 8
  draw('Income', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('Federal AGI', '1', `$${formatDollars(form.federalAGI)}`)
  if (form.nmSubtractions > 0) {
    drawLine('NM subtractions', '3', `($${formatDollars(form.nmSubtractions)})`)
  }
  drawLine('New Mexico AGI', '4', `$${formatDollars(form.nmAGI)}`, { bold: true })

  y -= 8
  draw('Deductions & Exemptions', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('NM standard deduction', '5', `$${formatDollars(form.nmStandardDeduction)}`)
  drawLine(`Personal exemptions (${form.numExemptions} x $4,150)`, '6', `$${formatDollars(form.personalExemptions)}`)
  drawLine('Taxable income', '8', `$${formatDollars(form.nmTaxableIncome)}`, { bold: true })

  y -= 8
  draw('Tax, Credits, and Payments', 72, 11, { font: fontBold, color: darkBlue })
  y -= 4
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.3, color: gray })
  y -= 16

  drawLine('NM tax (graduated)', '9', `$${formatDollars(form.nmTax)}`)
  if (form.nmEITC > 0) {
    drawLine('NM EITC (refundable)', '12', `$${formatDollars(form.nmEITC)}`)
  }
  drawLine('Tax after credits', '15', `$${formatDollars(form.taxAfterCredits)}`, { bold: true })
  if (form.stateWithholding > 0) {
    drawLine('NM withholding', '20', `$${formatDollars(form.stateWithholding)}`)
  }
  drawLine('Total payments', '25', `$${formatDollars(form.totalPayments)}`, { bold: true })

  y -= 8
  if (form.overpaid > 0) {
    drawLine('Refund', '30', `$${formatDollars(form.overpaid)}`, { bold: true })
  } else if (form.amountOwed > 0) {
    drawLine('Amount owed', '28', `$${formatDollars(form.amountOwed)}`, { bold: true })
  } else {
    drawLine('Balance', '', '$0')
  }

  y -= 20
  draw('Generated by OpenTax for review. File with official NM Form PIT-1.', 72, 7, { color: gray })

  return pdfDoc
}

export const nmFormCompiler: StateFormCompiler = {
  stateCode: 'NM',
  templateFiles: ['pit1.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as FormPIT1Result
    const doc = await generateFormPIT1(taxReturn, form)

    return {
      doc,
      forms: [{
        formId: stateResult.formLabel,
        sequenceNumber: 'NM-01',
        pageCount: doc.getPageCount(),
      }],
    }
  },
}
