/**
 * SC Form SC1040 PDF filler.
 *
 * Fills the official South Carolina SC1040 (Individual Income Tax Return)
 * template from computed SC1040 results. Falls back to programmatic
 * generation when no template is available.
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { SC1040Result } from '../../rules/2025/sc/sc1040'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic fallback generator ──────────────────────────────

async function generateSC1040(
  taxReturn: TaxReturn,
  form: SC1040Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.2, 0.45)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color: black })
  }

  const drawLine = (label: string, value: number) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, true)
    y -= 16
  }

  draw('South Carolina Form SC1040', 72, 16, true)
  y -= 14
  page.drawText('Individual Income Tax Return — 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: blue })
  y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 12
  draw(`Residency: ${form.residencyType}`, 72, 9)
  if (form.apportionmentRatio < 1) {
    draw(`Apportionment: ${(form.apportionmentRatio * 100).toFixed(1)}%`, 300, 9)
  }
  y -= 16

  draw('Income', 72, 11, true)
  y -= 16
  drawLine('Federal Taxable Income (1040 Line 15)', form.federalTaxableIncome)
  if (form.scAdditions > 0) drawLine('SC Additions', form.scAdditions)
  if (form.scSubtractions > 0) {
    drawLine('SC Subtractions', form.scSubtractions)
    if (form.socialSecuritySubtraction > 0) {
      draw(`  Social Security exemption`, 90, 8)
      draw(`$${formatDollars(form.socialSecuritySubtraction)}`, 470, 8)
      y -= 12
    }
    if (form.retirementIncomeDeduction > 0) {
      draw(`  Retirement income deduction`, 90, 8)
      draw(`$${formatDollars(form.retirementIncomeDeduction)}`, 470, 8)
      y -= 12
    }
    if (form.usGovInterestSubtraction > 0) {
      draw(`  US government interest`, 90, 8)
      draw(`$${formatDollars(form.usGovInterestSubtraction)}`, 470, 8)
      y -= 12
    }
    if (form.stateRefundSubtraction > 0) {
      draw(`  State/local tax refund`, 90, 8)
      draw(`$${formatDollars(form.stateRefundSubtraction)}`, 470, 8)
      y -= 12
    }
  }
  drawLine('SC Adjusted Gross Income', form.scAGI)

  y -= 8
  draw('Exemptions & Tax', 72, 11, true)
  y -= 16
  drawLine(`Personal Exemptions (${form.exemptionCount} x $4,700)`, form.exemptionAmount)
  drawLine('SC Taxable Income', form.scTaxableIncome)
  drawLine('SC Tax (3.99%)', form.scTax)

  if (form.scEITC > 0 || form.twoWageEarnerCredit > 0) {
    y -= 4
    draw('Credits', 72, 11, true)
    y -= 16
    if (form.scEITC > 0) drawLine('SC Earned Income Credit (41.67%)', form.scEITC)
    if (form.twoWageEarnerCredit > 0) drawLine('Two-Wage Earner Credit', form.twoWageEarnerCredit)
  }

  drawLine('Tax After Credits', form.taxAfterCredits)

  y -= 8
  draw('Payments', 72, 11, true)
  y -= 16
  drawLine('SC State Withholding', form.stateWithholding)

  y -= 8
  draw('Result', 72, 11, true)
  y -= 16
  if (form.overpaid > 0) drawLine('Refund', form.overpaid)
  else if (form.amountOwed > 0) drawLine('Amount You Owe', form.amountOwed)
  else drawLine('Balance', 0)

  y -= 20
  page.drawText('Generated by OpenTax — for review. File using official SC Form SC1040.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const scFormCompiler: StateFormCompiler = {
  stateCode: 'SC',

  templateFiles: ['sc1040.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as SC1040Result

    // Programmatic generation (template filling can be added later
    // once the AcroForm field names in the official SC1040 PDF are mapped)
    const doc = await generateSC1040(taxReturn, form)

    return {
      doc,
      forms: [
        {
          formId: 'SC Form SC1040',
          sequenceNumber: 'SC-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
