/**
 * UT Form TC-40 PDF filler.
 *
 * Fills the official Utah Form TC-40 (Individual Income Tax Return)
 * template from computed TC-40 results. Falls back to programmatic
 * generation when no template is available.
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TaxReturn } from '../../model/types'
import type { StateComputeResult } from '../../rules/stateEngine'
import type { TC40Result } from '../../rules/2025/ut/tc40'
import type { StateFormCompiler, StateFormTemplates, StateCompiledForms } from '../stateCompiler'
import { formatDollars, formatSSN, filingStatusLabel } from '../helpers'

// ── Programmatic fallback generator ──────────────────────────────

async function generateTC40(
  taxReturn: TaxReturn,
  form: TC40Result,
): Promise<PDFDocument> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const black = rgb(0, 0, 0)
  const gray = rgb(0.4, 0.4, 0.4)
  const blue = rgb(0.1, 0.2, 0.45)

  const page = pdfDoc.addPage([612, 792])
  let y = 750

  const draw = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, { x, y, size, font: bold ? fontBold : font, color: black })
  }

  const drawLine = (label: string, value: number) => {
    draw(label, 72, 10)
    draw(`$${formatDollars(value)}`, 460, 10, true)
    y -= 16
  }

  draw('Utah Form TC-40', 72, 16, true)
  y -= 14
  page.drawText('Individual Income Tax Return — 2025', { x: 72, y, size: 9, font, color: gray })
  y -= 8
  page.drawLine({ start: { x: 72, y }, end: { x: 540, y }, thickness: 0.4, color: blue })
  y -= 20

  const tp = taxReturn.taxpayer
  draw(`Name: ${tp.firstName} ${tp.lastName}`, 72, 9)
  y -= 12
  draw(`SSN: ${formatSSN(tp.ssn || '000000000')}`, 72, 9)
  draw(`Status: ${filingStatusLabel(taxReturn.filingStatus)}`, 300, 9)
  y -= 12

  if (form.residencyType !== 'full-year') {
    draw(`Residency: ${form.residencyType}`, 72, 9)
    draw(`Apportionment: ${(form.apportionmentRatio * 100).toFixed(1)}%`, 300, 9)
    y -= 12
  }

  y -= 4
  draw('Income', 72, 11, true)
  y -= 16
  drawLine('Federal AGI', form.federalAGI)
  if (form.utAdditions > 0) drawLine('UT Additions', form.utAdditions)
  if (form.utSubtractions > 0) drawLine('UT Subtractions', form.utSubtractions)
  drawLine('Utah Adjusted Income', form.utAdjustedIncome)
  drawLine('Utah Taxable Income', form.utTaxableIncome)

  y -= 8
  draw('Tax & Credits', 72, 11, true)
  y -= 16
  drawLine('Utah Tax (4.55%)', form.utTaxBeforeCredits)

  if (form.taxpayerTaxCredit > 0) {
    drawLine(`Taxpayer Tax Credit (${form.personalExemptionCount} persons)`, form.taxpayerTaxCredit)
  }
  if (form.utEITC > 0) drawLine('UT Earned Income Credit', form.utEITC)
  drawLine('Tax After Credits', form.taxAfterCredits)

  y -= 8
  draw('Payments', 72, 11, true)
  y -= 16
  drawLine('UT State Withholding', form.stateWithholding)

  y -= 8
  draw('Result', 72, 11, true)
  y -= 16
  if (form.overpaid > 0) drawLine('Refund', form.overpaid)
  else drawLine('Amount You Owe', form.amountOwed)

  y -= 20
  page.drawText('Generated by OpenTax — for review. File using official UT Form TC-40.', {
    x: 72, y, size: 7, font, color: gray,
  })

  return pdfDoc
}

// ── State Form Compiler ──────────────────────────────────────────

export const utFormCompiler: StateFormCompiler = {
  stateCode: 'UT',

  templateFiles: ['tc40.pdf'],

  async compile(
    taxReturn: TaxReturn,
    stateResult: StateComputeResult,
    _templates: StateFormTemplates,
  ): Promise<StateCompiledForms> {
    const form = stateResult.detail as TC40Result

    // For now, always use programmatic generation since the TC-40 PDF
    // field names need to be mapped. Template support can be added later
    // once field names are identified.
    const doc = await generateTC40(taxReturn, form)

    return {
      doc,
      forms: [
        {
          formId: 'UT Form TC-40',
          sequenceNumber: 'UT-01',
          pageCount: doc.getPageCount(),
        },
      ],
    }
  },
}
